# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apppack < Formula
  desc "CLI for AppPack.io"
  homepage "https://apppack.io"
  version "0.8.0"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/apppackio/apppack/releases/download/v0.8.0/apppack_0.8.0_Darwin_x86_64.tar.gz"
    sha256 "05c95dedf1a388f35933a711a3d55783018498c30ed651e2ea3b786c80a9aeb5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/apppackio/apppack/releases/download/v0.8.0/apppack_0.8.0_Linux_x86_64.tar.gz"
    sha256 "29cc32675f38cf6ccd1d5518feb4f0a506a7f7e7bf7288df2ca623a391d6c271"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/apppackio/apppack/releases/download/v0.8.0/apppack_0.8.0_Linux_arm64.tar.gz"
    sha256 "9d6e6303ee3d91b335aacf949ac74c2817c62a799571e47cfd665b007632d796"
  end

  def install
    bin.install "apppack"
  end

  test do
    system "#{bin}/apppack version"
  end
end
